### PR TITLE
Pinned Labelbase submodule to tag 2.2.0

### PR DESCRIPTION
**Pull request by xavierfiechter**
Thank you for making Labelbase available on Start9. 
Labelbase 2.2.0 was just released. I have updated the submodule with the corresponding tag.

### CODE REVIEW

**Comment by storopoli** [comment]
Thanks. I am still having some issues with repurposing the `docker-compose.yml` file to a single `Dockerfile`. That's how start9 works.
If you are able to check

https://github.com/CasaVinteUm/labelbase-startos/blob/0d538cd91da088289ad782ee5e4416e2298e341e/Dockerfile

that would be awesome.

**Comment by xavierfiechter** [comment]
Does it work as is?

Would it be simpler and more robust to run a shell script instead?

I'm currently working on the Raspiblitz integration, see here https://github.com/xavierfiechter/raspiblitz/blob/master/home.admin/config.scripts/bonus.labelbase.sh

**Comment by storopoli** [comment]
start-os is really Docker-centric.
I think it would be best (and easiest) to create a single Dockerfile (multi-stage build) from the Docker-Compose file.

**Comment by xavierfiechter** [comment]
Okay, but does labelbase-startos work as it is right now?

Sorry, I don't have a test device at hand at the moment.

**Comment by storopoli** [comment]
No it doesn't. I've merged #4 since it is 99% of the way.
You don't need start-os to test it. If you are able to make the Dockerfile work, in other words, if you do `docker run` and it runs labelbase successfully, then it will be very trivial for me to finish the packaging for start-os.

**Comment by storopoli** [comment]
The problem is not packaging it to start-os, but to convert the docker compose to a single dockerfile.
That dockerfile is consumed by start-os SDK to create the app.

**Comment by xavierfiechter** [comment]
Got it.

```
ENV MYSQL_USER=ulabelbase
ENV MYSQL_DATABASE=labelbase
ENV MYSQL_ROOT_PASSWORD=labelbase
ENV MYSQL_PASSWORD=labelbase
ENV MYSQL_PWD=labelbase
```

I don't particularly like that approach, yet many Dockerfiles include hard-coded passwords. That's why I implemented it using the Twelve-Factor App methodology, which resulted in an exports.sh file.

But hey, let's get this up and running. I'll check the Dockerfile as soon as possible.

**Comment by storopoli** [comment]
Yes that will change 😓 it will not be hardcoded.
The ideia is to expose that in the start-os GUI for the user to configure.
This is an example from the syncthing start-os package:

https://github.com/Start9Labs/syncthing-startos/blob/724b613c5e880e7476c93afd022d249f62a4b8d0/scripts/procedures/getConfig.ts#L3-L36

Edit: tracking on #7.

**Comment by xavierfiechter** [comment]
Awesome!

**Comment by xavierfiechter** [comment]
Could the Dockerfile also be named `Dockerfile.startos` or is the naming mandatory?

**Pull request merged**
